src/web/LZMotel.WebApp.MVC/Models/LoginViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LZMotel.WebApp.MVC.Models
{
  public class UsuarioLogin
  {
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [EmailAddress(ErrorMessage = "O campo {0} está em formato inválido")]
    public string Email { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 6)]
    public string Senha { get; set; }
  }

  public class UsuarioRespostaLogin
  {
    public string AccessToken { get; set; }
    public double ExpiresIn { get; set; }
    public UsuarioToken UsuarioToken { get; set; }
    public ResponseResult ResponseResult { get; set; }
  }

  public class UsuarioToken
  {
    public string Id { get; set; }
    public string Email { get; set; }
    public IEnumerable<UsuarioClaim> Claims { get; set; }
  }

  public class UsuarioClaim
  {
    public string Value { get; set; }
    public string Type { get; set; }
  }

}

src/web/LZMotel.WebApp.MVC/Controllers/IdentidadeController.cs
using LZMotel.WebApp.MVC.Models;
using LZMotel.WebApp.MVC.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Threading.Tasks;

namespace LZMotel.WebApp.MVC.Controllers
{
  public class IdentidadeController : MainController
  {
    private readonly IAutenticacaoService _autenticacaoService;
    public IdentidadeController(IAutenticacaoService autenticacaoService)
    {
      _autenticacaoService = autenticacaoService;
    }

    [HttpGet]
    [Route("")]
    [Route("login")]
    public IActionResult login(string returnUrl = null)
    {
      
      ViewData["ReturnUrl"] = returnUrl;
      return View();
    }

    [HttpPost]
    [Route("login")]
    public async Task<IActionResult> Login(UsuarioLogin usuarioLogin, string returnUrl = null)
    {
      ViewData["ReturnUrl"] = returnUrl;

      if (!ModelState.IsValid) return View(usuarioLogin);

      var resposta = await _autenticacaoService.Login(usuarioLogin);

      if (ResponsePossuiErros(resposta.ResponseResult)) return View(usuarioLogin);

      await RealizarLogin(resposta);

      if (string.IsNullOrEmpty(returnUrl)) return RedirectToAction("Index", controllerName: "Local");

      return LocalRedirect(returnUrl);
    }

    [HttpGet]
    [Route("sair")]
    public async Task<IActionResult> Logout()
    {
      await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
      return LocalRedirect("/login/");
    }

    private async Task RealizarLogin(UsuarioRespostaLogin resposta)
    {
      var token = ObterTokenFormatado(resposta.AccessToken);

      var claims = new List<Claim>();
      claims.Add(new Claim("JWT", resposta.AccessToken));
      claims.AddRange(token.Claims);
      
      var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

      var authProperties = new AuthenticationProperties
      {
        ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60),
        IsPersistent = true
      };

      await HttpContext.SignInAsync(
          CookieAuthenticationDefaults.AuthenticationScheme,
          new ClaimsPrincipal(claimsIdentity),
          authProperties);
    }

    private static JwtSecurityToken ObterTokenFormatado(string jwtToken)
    {
      return new JwtSecurityTokenHandler().ReadToken(jwtToken) as JwtSecurityToken;
    }
  }
}

src/web/LZMotel.WebApp.MVC/Views/Identidade/Login.cshtml
@model LZMotel.WebApp.MVC.Models.UsuarioLogin

@{
    Layout = "_Layoutlogin";
    ViewData["Title"] = "Log in";
}
<link href="~/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/css/Style.css" rel="stylesheet" />

<section>
    <div class="container-fluid no-gutters border">
        <div class="row">

            <div class="col image-login">
                @*<img class="img-fluid" src="~/theme/dist/img/photo1.png" alt="First slide">*@
            </div>
            <div class="col">
                <div class="login-tamanho vertical-center">
                    @*<figure class="figure">
                        <img class="img-fluid" src="~/theme/dist/img/LogoSaude.png" alt="First slide">
                    </figure>*@
                    <div class="text-center">
                        <h1 class="text-primary">LOVEIn</h1>
                        <h4 class="text-primary">Gestão de Motéis</h4>
                        <br />
                        <span><b class="text-primary">Olá! Acesse sua Conta WebAppMotel</b></span>
                        <p></p>
                    </div>
                    <form class="login-form" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">

                        <vc:Summary></vc:Summary>

                        <div class="form-group">
                            <label asp-for="Email" class="text-uppercase"></label>
                            <input asp-for="Email" class="form-control" placeholder="email@exemplo.com">
                            <span asp-validation-for="Email" class="text-danger"></span>

                        </div>

                        <div class="form-group">
                            <label asp-for="Senha"></label>
                            <input type="password" asp-for="Senha" class="form-control" placeholder="Sua senha" />
                            <span asp-validation-for="Senha" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-login float-right">Entrar</button>
                        </div>
                        <div class="form-group">
                            <p>
                                <a asp-action="Registro" asp-controller="Identidade">Criar uma conta</a>
                            </p>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/web/LZMotel.WebApp.MVC/Views/Identidade/Registro.cshtml
@model LZMotel.WebApp.MVC.Models.UsuarioRegistro
@{
    ViewData["Title"] = "Registro";
}

@*<div class="content-wrapper">
    <section class="content">
        <div class="tab-pane" id="settings">*@
<section class="section-conten padding-y container" style="min-height: 35vh">
    @*style="max-width: 640px; margin-top: 20px;*@
    <div class="card mx-auto" style="max-width: 640px; margin-top: 5px;">
        <div class="card-body">

            <vc:Summary></vc:Summary>

            <form class="form-horizontal" asp-controller="Identidade" asp-action="Registro"
                  asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">

                <div class="form-group row">
                    <label asp-for="Nome"></label>
                    <input asp-for="Nome" class="form-control">
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>

                <div class="form-group row">
                    <div class="col-md-6 mb-3">
                        <label asp-for="Cpf"></label>
                        <input asp-for="Cpf" class="form-control" placeholder="CPF">
                        <span asp-validation-for="Cpf" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6 mb-3">
                        <label asp-for="Turno"></label>
                        <input asp-for="Turno" class="form-control" placeholder="Turno">
                        <span asp-validation-for="Turno" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="Email"></label>
                    <input class="form-control" asp-for="Email" placeholder="Email">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group row">
                    <label asp-for="Funcao"></label>
                    <select class="form-control" asp-for="Funcao" placeholder="Funcao">
                        <option>ADMINISTRADOR</option>
                        <option>GERENTE</option>
                        <option>ATENDENTE</option>
                    </select>
                    <span asp-validation-for="Funcao" class="text-danger"></span>
                </div>

                <div class="form-group row">
                    <label asp-for="Senha"></label>
                    <input type="password" asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>

                <div class="form-group row">
                    <label asp-for="SenhaConfirmacao"></label>
                    <input type="password" asp-for="SenhaConfirmacao" class="form-control" />
                    <span asp-validation-for="SenhaConfirmacao" class="text-danger"></span>
                </div>

                <div class="form-group row">
                    <div class="offset-sm-3 col-sm-9">
                        <button type="submit" class="btn btn-primary btn-block">Registrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}