src/web/LZMotel.WebApp.MVC/Models/EnderecoViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace LZMotel.WebApp.MVC.Models
{
  public class EnderecoViewModel
    {
        [Required]
        public string Logradouro { get; set; }
        [Required]
        [DisplayName("Número")]
        public string Numero { get; set; }
        public string Complemento { get; set; }
        [Required]
        public string Bairro { get; set; }
        [Required]
        [DisplayName("CEP")]
        public string Cep { get; set; }
        [Required]
        public string Cidade { get; set; }
        [Required]
        public string Estado { get; set; }

        public override string ToString()
        {
            return $"{Logradouro}, {Numero} {Complemento} - {Bairro} - {Cidade} - {Estado}";
        }
    }
}

src/web/LZMotel.WebApp.MVC/Models/UsuarioViewModel.cs
using LZMotel.Core.DomainObjects;
using LZMotel.WebApp.MVC.Extensions;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace LZMotel.WebApp.MVC.Models
{
  public class UsuarioRegistro
  {
    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [DisplayName("Nome Completo")]
    public string Nome { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [DisplayName("CPF")]
    [Cpf]
    public string Cpf { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [DisplayName("Turno")]
    public string Turno { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [DisplayName("Função")]
    public Funcao Funcao { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [EmailAddress(ErrorMessage = "O campo {0} está em formato inválido")]
    public string Email { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 6)]
    public string Senha { get; set; }

    [DisplayName("Confirme sua senha")]
    [Compare("Senha", ErrorMessage = "As senhas não conferem.")]
    public string SenhaConfirmacao { get; set; }
    
    public IEnumerable<ClienteViewModel> Clientes { get; set; }
    public EnderecoViewModel Endereco { get; set; }
    public ResponseResult ResponseResult { get; set; }

  }
}

src/web/LZMotel.WebApp.MVC/Controllers/ClienteController.cs
using LZMotel.WebApp.MVC.Models;
using LZMotel.WebApp.MVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace LZMotel.WebApp.MVC.Controllers
{
  [Authorize]
  public class ClienteController : MainController
  {
    private readonly IClienteService _clienteService;

    public ClienteController(IClienteService clienteService)
    {
      _clienteService = clienteService;
    }

    [HttpGet]
    [Route("cliente/{id}")]
    public async Task<IActionResult> UsuarioIndex(Guid id)
    {
      var cliente = await _clienteService.ObterRegistroCliente(id);

      //if (ResponsePossuiErros(response) TempData["Erros"] =
      //    ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage)).ToList();
      //return View("Index", await _comprasBffService.ObterCarrinho());
      //return RedirectToAction("Usuario","Identidade",cliente);
      return View(cliente);
    }

    [HttpGet]
    [Route("novo-usuario")]
    public IActionResult Registro(string returnUrl = null)
    {
      return View();
    }

    [HttpPost]
    public async Task<IActionResult> NovoEndereco(EnderecoViewModel endereco)
    {
      var response = await _clienteService.AdicionarEndereco(endereco);

      if (ResponsePossuiErros(response)) TempData["Erros"] =
          ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage)).ToList();

      return RedirectToAction(actionName:"Index", controllerName:"Usuario");
    }

  }
}

src/web/LZMotel.WebApp.MVC/Controllers/LocalController.cs
using LZMotel.WebApp.MVC.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace LZMotel.WebApp.MVC.Controllers
{
  public class LocalController : MainController
  {
    private readonly ILocalService _localService;

    public LocalController(ILocalService localService)
    {
      _localService = localService;
    }

    [HttpGet]
    [Route("painel")]
    public async Task<IActionResult> Index()
    {
      var suites = await _localService.ObterTodos();

      return View(suites);
    }


    [HttpGet]
    [Route("suite-detalhe/{id}")]
    public async Task<IActionResult> SuiteDetalhe(Guid id)
    {
      var suite = await _localService.ObterPorId(id);

      return View(suite);
    }
  }
}

src/web/LZMotel.WebApp.MVC/Controllers/UsuarioController.cs
using LZMotel.WebApp.MVC.Models;
using LZMotel.WebApp.MVC.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LZMotel.WebApp.MVC.Controllers
{
  public class UsuarioController : MainController
  {
    private readonly IAutenticacaoService _autenticacaoService;
    private readonly IClienteService _clienteService;
    //private readonly IUsuarioService _usuarioService;
    public UsuarioController(IAutenticacaoService autenticacaoService, IClienteService clienteService
      )//IUsuarioService usuarioService)
    {
      _autenticacaoService = autenticacaoService;
      _clienteService = clienteService;
      //_usuarioService = usuarioService;
    }

    [HttpGet]
    [Route("usuarios")]
    public async Task<IActionResult> Index()
    {
      return View(await _clienteService.ObterTodosClientes());
    }

    [HttpPost]
    [Route("nova-conta")]
    public async Task<IActionResult> Registro(UsuarioRegistro usuarioRegistro, string returnUrl = null)
    {
      ViewData["ReturnUrl"] = returnUrl;

      if (!ModelState.IsValid) return View(usuarioRegistro);

      var resposta = await _autenticacaoService.Registro(usuarioRegistro);

      if (ResponsePossuiErros(resposta.ResponseResult)) return View(usuarioRegistro);

      //await RealizarLogin(resposta);

      return RedirectToAction("Usuario", controllerName: "Identidade",fragment: "registro");
      //return LocalRedirect("novo-usurio");
    }

  }
}

src/web/LZMotel.WebApp.MVC/Views/Usuario/Index.cshtml
@model LZMotel.WebApp.MVC.Models.UsuarioRegistro
@{
    ViewData["Title"] = "Cadastro de Usuário";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@ViewData["Title"]</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-controller="Local" asp-action="Index">Homel</a></li>
                        <li class="breadcrumb-item active">Usuario</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">

            <div class="container">
                <div class="row">
                    <div class="col-xs-12">

                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover table-condensed">
                                <thead>
                                    <tr class="active">
                                        @*<th>Id</th>*@
                                        <th>Nome Completo</th>
                                        <th>CPF</th>
                                        @*<th>EMAIL</th>*@
                                        <th>Turno</th>
                                        <th>Funcão</th>
                                        <th>Excluido?</th>
                                        <th>Comando</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        if (Model.Clientes.Any())
                                        {
                                            @foreach (var item in Model.Clientes)
                                            {
                                                <tr class="success">
                                                    <td>@item.Nome</td>
                                                    <td>@item.Cpf.Numero</td>
                                                    @*<td>@item.Email</td>*@
                                                    <td>@item.Turno</td>
                                                    <td>@item.Funcao</td>
                                                    <td>
                                                        @if (item.Excluido)
                                                        {
                                                            <span>SIM</span>
                                                        }
                                                        else
                                                        {
                                                            <span>NÃO</span>
                                                        }
                                                    </td>
                                                    <td>
                                                        <a asp-action="Editar" asp-route-id="@item.Id">Editar</a> |
                                                        <a asp-action="Excluir" asp-route-id="@item.Id">Excluir</a> |
                                                        <partial name="_Endereco" model="Model" />
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    }
                                </tbody>
                            </table>

                            <partial name="_NovoEndereco" />
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </section>
</div>
@section Scripts {

    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
       $(document).ready(function() {
          BuscaCep();
       });
    </script>
}

src/web/LZMotel.WebApp.MVC/Views/Usuario/_Endereco.cshtml
@model LZMotel.WebApp.MVC.Models.UsuarioRegistro

@{
    if (Model.Endereco == null)
    {
        <a href="javascript:void(0)" data-toggle="modal" data-target="#enderecoModal">Adicionar Endereço</a>
    }
    else
    {
        <a href="javascript:void(0)" data-toggle="tooltip" title="@Model.Endereco.ToString()" data-placement="left"
           class="btn btn-primary float-md-right"> <i class="fa fa-location-arrow"></i> Alterar Endereço</a>
    }
}

src/web/LZMotel.WebApp.MVC/Views/Usuario/_NovoEndereco.cshtml
@model LZMotel.WebApp.MVC.Models.UsuarioRegistro
@{
    ViewData["Title"] = "Novo Endereço";
}

    <div class="modal fade" id="enderecoModal" tabindex="-1" role="dialog" aria-labelledby="enderecoModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div id="myModalContent">

                    <div class="modal-header">
                        <h4 class="modal-title">@ViewData["Title"]</h4>
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">×</span><span class="sr-only">Fechar</span>
                        </button>
                    </div>
                    
                    <form asp-action="NovoEndereco" asp-controller="Cliente">
                        <div class="modal-body">

                            <div class="form-group">
                                <label asp-for="Endereco.Cep"></label>
                                <input asp-for="Endereco.Cep" class="form-control" />
                                <span asp-validation-for="Endereco.Cep" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Logradouro"></label>
                                <input asp-for="Endereco.Logradouro" class="form-control" />
                                <span asp-validation-for="Endereco.Logradouro" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Numero"></label>
                                <input asp-for="Endereco.Numero" class="form-control" />
                                <span asp-validation-for="Endereco.Numero" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Complemento"></label>
                                <input asp-for="Endereco.Complemento" class="form-control" />
                                <span asp-validation-for="Endereco.Complemento" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Bairro"></label>
                                <input asp-for="Endereco.Bairro" class="form-control" />
                                <span asp-validation-for="Endereco.Bairro" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Cidade"></label>
                                <input asp-for="Endereco.Cidade" class="form-control" />
                                <span asp-validation-for="Endereco.Cidade" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Endereco.Estado"></label>
                                <input asp-for="Endereco.Estado" class="form-control" />
                                <span asp-validation-for="Endereco.Estado" class="text-danger"></span>
                            </div>

                            <div class="modal-footer">
                                <div>
                                    <input type="submit" value="Cadastrar Endereço" class="btn btn-success" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

<script>
    BuscaCep();
</script>